package com.dw.utils;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;

import javax.swing.JTabbedPane;
import javax.swing.table.TableColumnModel;

import org.jdesktop.swingx.JXDatePicker;

import com.dw.editor.DCTableEditor;
import com.dw.model.DCTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author samuel
 */
public class CreateDCPanel extends javax.swing.JFrame {
	static int rcnt = 0;

	/**
	 * Creates new form CreateDCPanel
	 */
	public CreateDCPanel(JTabbedPane jTabbedPane1) {
		initComponents();
		dateP.setDate(Calendar.getInstance().getTime());
		dateP.setFormats(new SimpleDateFormat("dd/MM/yyyy"));

		dateOP.setDate(Calendar.getInstance().getTime());
		dateOP.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
		jButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub

				// TODO Auto-generated method stub

				jTabbedPane1.setEnabledAt(0, true);
				jTabbedPane1.setEnabledAt(1, true);
				jTabbedPane1.setEnabledAt(2, false);
				jTabbedPane1.setEnabledAt(3, false);
				jTabbedPane1.setEnabledAt(4, false);
				jTabbedPane1.setEnabledAt(5, false);

				jTabbedPane1.getModel().setSelectedIndex(1);

			}
		});

		jButton3.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				ArrayList<String> row = new ArrayList<>();
				rcnt++;
				row.add(rcnt+"");
				row.add(desTF.getText());
				row.add(descriptionTF.getText());
				row.add(jComboBox1.getSelectedItem().toString());
				row.add(rTF.getText());
				row.add(rMTF.getText());
				dcModel.add(row);
			}
		});

		jButton5.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				snoTF.setText("");
				desTF.setText("");
				descriptionTF.setText("");
				rTF.setText("");
				rMTF.setText("");
			}
		});

		jButton4.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				int rowNo = dcTable.getSelectedRow();
				if (rowNo != -1) {
					dcModel.getModel().remove(dcTable.getSelectedRow());
					dcModel.fireTableDataChanged();
				}
			}
		});

	}

	/**
	 * Creates new form CreateDCPanel
	 */
	public CreateDCPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		dcPanel = new javax.swing.JPanel();
		dateP.setFont(new java.awt.Font("Ubuntu", 0, 18));
		dateOP.setFont(new java.awt.Font("Ubuntu", 0, 18));
		DeleveryChallanPanel = new javax.swing.JPanel();
		propertiersPanel = new javax.swing.JPanel();
		noL = new javax.swing.JLabel();
		noL.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18));
		orderNoTF = new javax.swing.JTextField();
		orderNoTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		orderNoTF.setColumns(5);
		companyTF = new javax.swing.JTextField();
		companyTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		companyTF.setColumns(5);

		desTF = new javax.swing.JTextField();
		desTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		desTF.setColumns(5);

		descriptionTF = new javax.swing.JTextField();
		descriptionTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		descriptionTF.setColumns(5);

		snoTF = new javax.swing.JTextField();
		snoTF.setEditable(false);
		snoTF.setEnabled(false);
		snoTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		snoTF.setColumns(5);

		noTF = new javax.swing.JTextField();
		noTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		noTF.setColumns(5);

		rMTF = new javax.swing.JTextField();
		rMTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		rMTF.setColumns(5);

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton3 = new javax.swing.JButton();
		jButton3.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton4 = new javax.swing.JButton();
		jButton4.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel10 = new javax.swing.JLabel();
		jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel11 = new javax.swing.JLabel();
		jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		rTF = new javax.swing.JTextField();
		rTF.setFont(new java.awt.Font("Ubuntu", 0, 18));
		rTF.setColumns(5);

		jLabel14 = new javax.swing.JLabel();
		jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 18));

		jTextField11 = new javax.swing.JTextField();
		jTextField11.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTextField11.setColumns(5);

		jButton5 = new javax.swing.JButton();
		jButton5.setFont(new java.awt.Font("Ubuntu", 0, 18));
		tableContainer = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		dcTable = new javax.swing.JTable();
		dcTable.setFont(new java.awt.Font("Ubuntu", 0, 18));
		dcTable.getTableHeader().setFont(new java.awt.Font("Ubuntu", 0, 18));
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton2 = new javax.swing.JButton();
		jButton2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		dcPanel.setLayout(new java.awt.GridBagLayout());

		DeleveryChallanPanel.setLayout(new java.awt.GridBagLayout());

		propertiersPanel.setLayout(new java.awt.GridBagLayout());

		noL.setText("No:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.weightx = 0.2;
		propertiersPanel.add(noL, gridBagConstraints);

		jLabel3.setText("Order No:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		propertiersPanel.add(jLabel3, gridBagConstraints);

		jLabel4.setText("Description:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		propertiersPanel.add(jLabel4, gridBagConstraints);

		jLabel5.setText("Order Date:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		propertiersPanel.add(jLabel5, gridBagConstraints);

		jLabel6.setText("Date:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.weightx = 0.2;
		propertiersPanel.add(jLabel6, gridBagConstraints);

		jLabel7.setText("Remarks:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 8;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.weightx = 0.05;
		propertiersPanel.add(jLabel7, gridBagConstraints);

		jLabel8.setText("Qty:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		propertiersPanel.add(jLabel8, gridBagConstraints);

		orderNoTF.setText("orderNoTF");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		propertiersPanel.add(orderNoTF, gridBagConstraints);

		companyTF.setText("companyTF");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 7;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		propertiersPanel.add(dateOP, gridBagConstraints);

		desTF.setText("orderDateTF");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		propertiersPanel.add(desTF, gridBagConstraints);

		descriptionTF.setText("descriptionTF");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		propertiersPanel.add(descriptionTF, gridBagConstraints);

		snoTF.setText("qtyTF");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.weightx = 0.2;
		propertiersPanel.add(snoTF, gridBagConstraints);

		noTF.setText("noTF");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.weightx = 0.2;
		propertiersPanel.add(dateP, gridBagConstraints);

		rMTF.setText("jTextField7");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.weightx = 0.05;
		propertiersPanel.add(rMTF, gridBagConstraints);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT,
						javax.swing.border.TitledBorder.DEFAULT_POSITION),
				"To M/s", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 18))); // NOI18N
		jScrollPane1.setViewportView(jTextArea1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 10;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 7;
		gridBagConstraints.gridheight = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.weightx = 0.2;
		propertiersPanel.add(jScrollPane1, gridBagConstraints);

		jButton3.setText("AddItem");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 10;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		propertiersPanel.add(jButton3, gridBagConstraints);

		jButton4.setText("DeleteItem");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 11;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		propertiersPanel.add(jButton4, gridBagConstraints);

		jLabel10.setText("Per:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		propertiersPanel.add(jLabel10, gridBagConstraints);

		jLabel11.setText("     Rate:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		propertiersPanel.add(jLabel11, gridBagConstraints);

		jComboBox1.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		propertiersPanel.add(jComboBox1, gridBagConstraints);

		rTF.setText("remarks");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 7;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		propertiersPanel.add(rTF, gridBagConstraints);

		jLabel14.setText("Company Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 8;
		gridBagConstraints.gridy = 0;
		propertiersPanel.add(jLabel14, gridBagConstraints);

		jTextField11.setText("PexaByte");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 9;
		gridBagConstraints.gridy = 0;
		propertiersPanel.add(jTextField11, gridBagConstraints);

		jButton5.setText("Clear");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 12;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		propertiersPanel.add(jButton5, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.5;
		DeleveryChallanPanel.add(propertiersPanel, gridBagConstraints);

		tableContainer.setLayout(new java.awt.BorderLayout());

		jScrollPane2.setBorder(
				javax.swing.BorderFactory.createTitledBorder(null, "AddedItems", javax.swing.border.TitledBorder.LEFT,
						javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 18)));

		dcTable.setModel(dcModel);
		jScrollPane2.setViewportView(dcTable);

		/**
		 * Editor & Renderer
		 */
		TableColumnModel columnModel = dcTable.getColumnModel();
		int len = columnModel.getColumnCount();
		for (int i = 0; i < len; i++) {
			dcTable.setDefaultEditor(columnModel.getColumn(i).getClass(), dcEditor);
		}

		tableContainer.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		jButton1.setText("Create DeleveryChallan");
		jPanel1.add(jButton1);

		jButton2.setText("Cancel");
		jPanel1.add(jButton2);

		tableContainer.add(jPanel1, java.awt.BorderLayout.PAGE_END);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.5;
		DeleveryChallanPanel.add(tableContainer, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.9;
		dcPanel.add(DeleveryChallanPanel, gridBagConstraints);

		jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("RAMANA  ENGINEERING WORKS");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.1;
		dcPanel.add(jLabel1, gridBagConstraints);

		getContentPane().add(dcPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CreateDCPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CreateDCPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CreateDCPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CreateDCPanel.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CreateDCPanel().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JPanel DeleveryChallanPanel;
	private javax.swing.JPanel dcPanel;

	public javax.swing.JPanel getDcPanel() {
		return dcPanel;
	}

	public void setDcPanel(javax.swing.JPanel dcPanel) {
		this.dcPanel = dcPanel;
	}

	private javax.swing.JButton createB;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton addItem;
	private javax.swing.JButton deleteItemB;
	private javax.swing.JButton jButton5;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel noL;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel companyL;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable dcTable;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField orderNoTF;
	private javax.swing.JTextField companyTF;
	private javax.swing.JTextField rTF;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField desTF;
	private javax.swing.JTextField descriptionTF;
	private javax.swing.JTextField snoTF;
	private javax.swing.JTextField noTF;
	JXDatePicker dateP = new JXDatePicker();
	JXDatePicker dateOP = new JXDatePicker();

	private javax.swing.JTextField dateTF;
	private javax.swing.JTextField remarksTF;
	private javax.swing.JTextField rMTF;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private javax.swing.JTextField rateTF;
	private javax.swing.JPanel propertiersPanel;
	private javax.swing.JPanel tableContainer;

	private DCTableModel dcModel = new DCTableModel();
	private DCTableEditor dcEditor = new DCTableEditor();
	// End of variables declaration
}
