package com.dw.utils;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author samuel
 */
public class HomePanel extends javax.swing.JFrame {
	javax.swing.JTabbedPane jTabbedPane1 = null;
	CreateDCPanel cdPanel=null;
	public CreateDCPanel getCdPanel() {
		return cdPanel;
	}

	public void setCdPanel(CreateDCPanel cdPanel) {
		this.cdPanel = cdPanel;
	}

	/**
	 * Creates new form HomePanel
	 */
	public HomePanel() {
		initComponents();
	}
	// jTable2

	public HomePanel(JTable table, javax.swing.JTabbedPane jTabbedPane) {
		this.jTable2 = table;
		initComponents();
		jTabbedPane1 = jTabbedPane;
		jButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub

				jTabbedPane1.setEnabledAt(0, true);
				jTabbedPane1.setEnabledAt(1, false);
				jTabbedPane1.setEnabledAt(2, true);
				jTabbedPane1.setEnabledAt(3, false);
				jTabbedPane1.setEnabledAt(4, false);
				jTabbedPane1.setEnabledAt(5, false);

				cdPanel.getjButton1().setText("Save");
				cdPanel.getjButton2().setText("Cancel");
				jTabbedPane1.getModel().setSelectedIndex(2);

			}
		});
		jButton4.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("LoadDelievryChallan do here");
			}
		});
		jButton4.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("EDIT DelievryChallan do here");
			}
		});
		jButton6.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("Delete DelievryChallan do here");
			}
		});
		jButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("EDIT INOICE..do here");
			}
		});
		jButton7.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("DELETE INOICE..do here");
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		toplevelPanel = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel6 = new javax.swing.JLabel();
		jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jComboBox2 = new javax.swing.JComboBox<>();
		jComboBox2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton4 = new javax.swing.JButton();
		jButton4.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton5 = new javax.swing.JButton();
		jButton5.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton6 = new javax.swing.JButton();
		jButton6.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jPanel3 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		// jTable2 = new javax.swing.JTable();
		jPanel4 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTextField1 = new javax.swing.JTextField();
		jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTextField2 = new javax.swing.JTextField();
		jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTextField3 = new javax.swing.JTextField();
		jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 18));

		jButton2 = new javax.swing.JButton();
		jButton2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton7 = new javax.swing.JButton();
		jButton7.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jPanel5 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextPane2 = new javax.swing.JTextPane();
		jTextPane2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jTextPane1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton3 = new javax.swing.JButton();
		jButton3.setFont(new java.awt.Font("Ubuntu", 0, 18));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		toplevelPanel.setLayout(new java.awt.GridBagLayout());

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Challan",
				javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Ubuntu", 0, 18)));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jButton1.setText("Create Delivery Challan");
		jPanel1.add(jButton1, new java.awt.GridBagConstraints());

		jLabel6.setText("M/s");
		jPanel1.add(jLabel6, new java.awt.GridBagConstraints());

		jComboBox2.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		jPanel1.add(jComboBox2, new java.awt.GridBagConstraints());

		jButton4.setText("LoadDelievryChallan");
		jPanel1.add(jButton4, new java.awt.GridBagConstraints());

		jButton5.setText("EDIT DelievryChallan");
		jPanel1.add(jButton5, new java.awt.GridBagConstraints());

		jButton6.setText("Delete DelievryChallan");
		jPanel1.add(jButton6, new java.awt.GridBagConstraints());

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.2;
		toplevelPanel.add(jPanel1, gridBagConstraints);

		jPanel3.setLayout(new java.awt.BorderLayout());

		jScrollPane2.setViewportView(jTable2);

		jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.3;
		toplevelPanel.add(jPanel3, gridBagConstraints);

		jPanel4.setBorder(
				javax.swing.BorderFactory.createTitledBorder(null, "Invoice", javax.swing.border.TitledBorder.LEFT,
						javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 0, 18)));
		jPanel4.setLayout(new java.awt.GridBagLayout());

		jPanel2.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("INVOICE NO:");
		jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

		jTextField1.setText("jTextField1");
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		jPanel2.add(jTextField1, new java.awt.GridBagConstraints());

		jButton2.setText("EDIT");
		jPanel2.add(jButton2, new java.awt.GridBagConstraints());

		jButton7.setText("DELETE");
		jPanel2.add(jButton7, new java.awt.GridBagConstraints());

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel2, gridBagConstraints);

		jPanel5.setLayout(new java.awt.GridBagLayout());

		jLabel3.setText("Service Tax:");
		jPanel5.add(jLabel3, new java.awt.GridBagConstraints());

		jComboBox1.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		jPanel5.add(jComboBox1, new java.awt.GridBagConstraints());
		jScrollPane3.setViewportView(jTextPane2);
		jTextField2.setText("%");
		jPanel5.add(jTextField2, new java.awt.GridBagConstraints());

		jLabel5.setText("%");
		jPanel5.add(jLabel5, new java.awt.GridBagConstraints());

		jLabel4.setText("Party TIN No:");
		jPanel5.add(jLabel4, new java.awt.GridBagConstraints());

		jScrollPane1.setViewportView(jTextPane1);
		jTextField3.setText("TIN");
		jTextField3.setColumns(15);
		jPanel5.add(jTextField3);

		jButton3.setText("Generate Invoice");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel5.add(jButton3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        toplevelPanel.add(jPanel4, gridBagConstraints);

        getContentPane().add(toplevelPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:

		// TODO Auto-generated method stub

		jTabbedPane1.setEnabledAt(0, true);
		jTabbedPane1.setEnabledAt(1, false);
		jTabbedPane1.setEnabledAt(2, false);
		jTabbedPane1.setEnabledAt(3, true);
		jTabbedPane1.setEnabledAt(4, false);
		jTabbedPane1.setEnabledAt(5, false);

		jTabbedPane1.getModel().setSelectedIndex(3);

	}// GEN-LAST:event_jButton3ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomePanel().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextPane jTextPane1;
	private javax.swing.JTextPane jTextPane2;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JPanel toplevelPanel;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JPanel getToplevelPanel() {
		return toplevelPanel;
	}

	public void setToplevelPanel(javax.swing.JPanel toplevelPanel) {
		this.toplevelPanel = toplevelPanel;
	}
}
