/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pb.re.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.JOptionPane;

import com.dw.model.CustomerTableModel;
import com.dw.model.ItemDetailsTableModel;
import com.dw.utils.CreateDCPanel;
import com.dw.utils.CreateINVPanel;
import com.dw.utils.HomePanel;

/**
 *
 * @author samuel
 */
public class TopLevelContainer extends javax.swing.JFrame {

	ItemDetailsTableModel model = new ItemDetailsTableModel();
	CustomerTableModel customerTableModel = new CustomerTableModel();
	CreateINVPanel cp = null;

	/**
	 * Creates new form TopLevelContainer
	 */
	public TopLevelContainer() {

		initComponents();
		jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTabbedPane1.setEnabledAt(1, false);
		jTabbedPane1.setEnabledAt(2, false);
		jTabbedPane1.setEnabledAt(3, false);
		jTabbedPane1.setEnabledAt(4, false);
		jTabbedPane1.setEnabledAt(5, false);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel7 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton1 = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jPanel2 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		jPanel10 = new javax.swing.JPanel();
		jPanel12 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton3 = new javax.swing.JButton();
		jPanel11 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jTable2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTable2.getTableHeader().setFont(new java.awt.Font("Ubuntu", 0, 18));
		jPanel3 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jPanel9 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		dateOfDepositTextField = new javax.swing.JTextField();
		addresss1_textField = new javax.swing.JTextField();
		itemNameTextField = new javax.swing.JTextField();
		principalAmountTextField = new javax.swing.JTextField();
		addresss3_textField = new javax.swing.JTextField();
		addresss2_textField = new javax.swing.JTextField();
		customerName = new javax.swing.JTextField();
		itemWeightTextField = new javax.swing.JTextField();
		quantityTextField = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		itemsList = new javax.swing.JComboBox();
		fatherNameTextField = new javax.swing.JTextField();
		createCustomerButton = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel12 = new javax.swing.JLabel();
		rateOfInterestTextField = new javax.swing.JTextField();
		CreateDCPanel delevaryPanel = new CreateDCPanel(jTabbedPane1);

		jPanel4 = delevaryPanel.getDcPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setLayout(new java.awt.BorderLayout());

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
		jLabel1.setText("RAMANA ENGINEERNG WORKS LOGIN");
		jLabel1.setMaximumSize(new java.awt.Dimension(148, 50));
		jLabel1.setMinimumSize(new java.awt.Dimension(148, 50));
		jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

		jPanel7.setLayout(new java.awt.GridBagLayout());

		jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel2.setText("UserName");
		jPanel7.add(jLabel2, new java.awt.GridBagConstraints());

		jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel3.setText("PassWord");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		jPanel7.add(jLabel3, gridBagConstraints);

		jTextField1.setText("username");
		jTextField1.setColumns(10);
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel7.add(jTextField1, gridBagConstraints);
		jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton1.setText("Login");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		jPanel7.add(jButton1, gridBagConstraints);

		jPasswordField1.setText("jPasswordField1");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel7.add(jPasswordField1, gridBagConstraints);

		jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

		jTabbedPane1.addTab("Login", jPanel1);

		jPanel2.setLayout(new java.awt.BorderLayout());

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24));
		jLabel4.setText("HOME");
		jPanel2.add(jLabel4, java.awt.BorderLayout.PAGE_START);

		jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel8.setLayout(new java.awt.GridBagLayout());

		jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Customer",
				javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Ubuntu", 0, 18)));
		jPanel10.setLayout(new java.awt.GridBagLayout());

		jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel6.setText("Customer Name:");
		jPanel12.add(jLabel6);

		jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTextField3.setText("jTextField3");
		jPanel12.add(jTextField3);

		jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jLabel5.setText("Customer Id:");
		jPanel12.add(jLabel5);

		jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jTextField2.setText("jTextField2");
		jPanel12.add(jTextField2);

		jButton3.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton3.setText("Search");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel12.add(jButton3);

		jPanel10.add(jPanel12, new java.awt.GridBagConstraints());

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel8.add(jPanel10, gridBagConstraints);

		jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Customer",
				javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Ubuntu", 0, 18)));

		jButton2.setFont(new java.awt.Font("Ubuntu", 0, 18));
		jButton2.setText("Create New Customer");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel11.add(jButton2);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel8.add(jPanel11, gridBagConstraints);

		jTable2.setModel(customerTableModel);
		jScrollPane2.setViewportView(jTable2);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel8.add(jScrollPane2, gridBagConstraints);

		HomePanel searchPanel = new HomePanel(jTable2,jTabbedPane1);

		jPanel2.add(searchPanel.getToplevelPanel(), java.awt.BorderLayout.CENTER);

		jTabbedPane1.addTab("Home", jPanel2);

		jPanel3.setLayout(new java.awt.BorderLayout());

		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24));
		jLabel7.setText("RAMANA ENGINEERING WORKS");
		jPanel3.add(jLabel7, java.awt.BorderLayout.PAGE_START);

		jPanel9.setLayout(new java.awt.GridBagLayout());

		jLabel8.setText("Customer Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel8, gridBagConstraints);

		jLabel9.setText("Date Of Deposite:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel9, gridBagConstraints);

		jLabel10.setText("Address_1:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel10, gridBagConstraints);

		jLabel11.setText("Item Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel11, gridBagConstraints);

		jLabel13.setText("Rate Of Interest:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel13, gridBagConstraints);

		jLabel15.setText("Address_3:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel15, gridBagConstraints);

		jLabel16.setText("Quantity:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel16, gridBagConstraints);

		jLabel19.setText("Metal:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel19, gridBagConstraints);

		jLabel20.setText("Address_2:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel20, gridBagConstraints);

		dateOfDepositTextField.setText("jTextField4");
		dateOfDepositTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dateOfDepositTextFieldActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 0.3;
		jPanel9.add(dateOfDepositTextField, gridBagConstraints);

		addresss1_textField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 0.3;
		jPanel9.add(addresss1_textField, gridBagConstraints);

		itemNameTextField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 0.3;
		jPanel9.add(itemNameTextField, gridBagConstraints);

		principalAmountTextField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(principalAmountTextField, gridBagConstraints);

		addresss3_textField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(addresss3_textField, gridBagConstraints);

		addresss2_textField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(addresss2_textField, gridBagConstraints);

		customerName.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		gridBagConstraints.weightx = 0.3;
		jPanel9.add(customerName, gridBagConstraints);

		itemWeightTextField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(itemWeightTextField, gridBagConstraints);

		quantityTextField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 7;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(quantityTextField, gridBagConstraints);

		jLabel21.setText("Father Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel21, gridBagConstraints);

		jLabel22.setText("Item Weight:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel22, gridBagConstraints);

		itemsList.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(itemsList, gridBagConstraints);

		fatherNameTextField.setText("jTextField17");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(fatherNameTextField, gridBagConstraints);

		createCustomerButton.setText("Create Customer");
		createCustomerButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createCustomerButtonActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 8;
		jPanel9.add(createCustomerButton, gridBagConstraints);

		jButton5.setText("Cancel");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 8;
		jPanel9.add(jButton5, gridBagConstraints);

		jButton7.setText("Add Item");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 8;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jButton7, gridBagConstraints);

		jTable1.setModel(model);
		jScrollPane1.setViewportView(jTable1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.gridwidth = 14;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel9.add(jScrollPane1, gridBagConstraints);

		jLabel12.setText("Principal Amount");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(jLabel12, gridBagConstraints);

		rateOfInterestTextField.setText("jTextField4");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel9.add(rateOfInterestTextField, gridBagConstraints);

		/*
		 * javax.swing.GroupLayout jPanel4Layout = new
		 * javax.swing.GroupLayout(jPanel4); jPanel4.setLayout(jPanel4Layout);
		 * jPanel4Layout.setHorizontalGroup(
		 * jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
		 * LEADING) .addGap(0, 724, Short.MAX_VALUE) );
		 * jPanel4Layout.setVerticalGroup(
		 * jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.
		 * LEADING) .addGap(0, 353, Short.MAX_VALUE) );
		 */
		jTabbedPane1.addTab("Delevary Challan", jPanel4);

		cp = new CreateINVPanel(jTabbedPane1);

		jPanel3.add(cp.getjPanel4(), java.awt.BorderLayout.CENTER);
		jTabbedPane1.addTab("Create", jPanel3);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 724, Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 353, Short.MAX_VALUE));

		jTabbedPane1.addTab("tab5", jPanel5);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 724, Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 353, Short.MAX_VALUE));

		jTabbedPane1.addTab("tab6", jPanel6);

		getContentPane().add(jTabbedPane1, BorderLayout.CENTER);

		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		setBounds(0, 0, screenSize.width, screenSize.height);
		setVisible(true);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		String userName = jTextField1.getText();
		char passwordc[] = jPasswordField1.getPassword();
		String pwdS = new String(passwordc);
		if (userName.equals("Admin") && pwdS.equals("Admin")) {
			jTabbedPane1.setEnabledAt(0, true);
			jTabbedPane1.setEnabledAt(1, true);
			jTabbedPane1.setEnabledAt(2, false);
			jTabbedPane1.setEnabledAt(3, false);
			jTabbedPane1.setEnabledAt(4, false);
			jTabbedPane1.setEnabledAt(5, false);

			jTabbedPane1.getModel().setSelectedIndex(1);

		} else {
			JOptionPane.showMessageDialog(rootPane, "Invalid credentials..");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:
		ArrayList<String> aux = new ArrayList<String>();
		aux.add(itemNameTextField.getText());
		aux.add((String) itemsList.getSelectedItem());
		aux.add(itemWeightTextField.getText());
		aux.add(quantityTextField.getText());
		aux.add(principalAmountTextField.getText());
		model.addRow(aux);

	}// GEN-LAST:event_jButton7ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		model.getModel().clear();
		jTabbedPane1.getModel().setSelectedIndex(2);
		// cp.getjLabel45().setText(customerName.getText());

	}// GEN-LAST:event_jButton2ActionPerformed

	private void dateOfDepositTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dateOfDepositTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_dateOfDepositTextFieldActionPerformed

	private void createCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {
	}// GEN-LAST:event_createCustomerButtonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TopLevelContainer.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TopLevelContainer.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TopLevelContainer.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TopLevelContainer.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TopLevelContainer().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField addresss1_textField;
	private javax.swing.JTextField addresss2_textField;
	private javax.swing.JTextField addresss3_textField;
	private javax.swing.JButton createCustomerButton;
	private javax.swing.JTextField customerName;
	private javax.swing.JTextField dateOfDepositTextField;
	private javax.swing.JTextField fatherNameTextField;
	private javax.swing.JTextField itemNameTextField;
	private javax.swing.JTextField itemWeightTextField;
	private javax.swing.JComboBox itemsList;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField principalAmountTextField;
	private javax.swing.JTextField quantityTextField;
	private javax.swing.JTextField rateOfInterestTextField;
	// End of variables declaration//GEN-END:variables
}
